-- HATRO:X - Database Schema for XAMPP (MySQL)
-- Requirements: MySQL 5.7+ / 8+

DROP DATABASE IF EXISTS hatrox_db;
CREATE DATABASE hatrox_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE hatrox_db;

-- product_ratings table
CREATE TABLE IF NOT EXISTS product_ratings (
  id INT AUTO_INCREMENT PRIMARY KEY,
  product_id INT NOT NULL,
  user_id INT NULL,
  rating INT NOT NULL,
  comment TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_ratings_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
  CONSTRAINT fk_ratings_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
  CHECK (rating BETWEEN 1 AND 5)
) ENGINE=InnoDB;

-- Users table
CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  full_name VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  remember_token VARCHAR(255) NULL,
  is_admin TINYINT(1) NOT NULL DEFAULT 0,
  is_blocked TINYINT(1) NOT NULL DEFAULT 0
) ENGINE=InnoDB;

-- Products table
CREATE TABLE products (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  discount_percent INT NOT NULL DEFAULT 0,
  image_url VARCHAR(255) NOT NULL,
  category VARCHAR(50) NOT NULL,
  stock_quantity INT NOT NULL DEFAULT 0,
  sold_count INT NOT NULL DEFAULT 0,
  created_by INT NOT NULL,
  status ENUM('active','pending') NOT NULL DEFAULT 'pending',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_products_user 
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;


-- Cart table
CREATE TABLE cart (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  product_id INT NOT NULL,
  quantity INT NOT NULL DEFAULT 1,
  CONSTRAINT fk_cart_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_cart_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
  UNIQUE KEY uniq_user_product (user_id, product_id)
) ENGINE=InnoDB;

-- Orders table
CREATE TABLE orders (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  total_amount DECIMAL(10,2) NOT NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'pending',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Order items table
CREATE TABLE order_items (
  id INT AUTO_INCREMENT PRIMARY KEY,
  order_id INT NOT NULL,
  product_id INT NOT NULL,
  quantity INT NOT NULL,
  price_at_time DECIMAL(10,2) NOT NULL,
  CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
  CONSTRAINT fk_order_items_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE RESTRICT
) ENGINE=InnoDB;

-- Comments table (for testimonials)
CREATE TABLE comments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NULL,
  user_name VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL,
  comment_text TEXT NOT NULL,
  rating INT NOT NULL CHECK (rating BETWEEN 1 AND 5),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  is_approved TINYINT(1) NOT NULL DEFAULT 0,
  is_hidden TINYINT(1) NOT NULL DEFAULT 0,
  CONSTRAINT fk_comments_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;

-- Default admin account (email: error@hatrox.com, password: error)
-- Password hash generated by PHP password_hash('error', PASSWORD_DEFAULT)
INSERT INTO users (full_name, email, password_hash, is_admin) VALUES
('Administrator', 'error@hatrox.com', '$2y$10$H0qv7f8S3l1Qh0wXJr3yuebp0y0m0bYF9w0s5q9l9kR3z1ZV2Zx4m', 1);

-- Sample products (pending by default)
INSERT INTO products (name, description, price, image_url, category, stock_quantity, created_by, status) VALUES
('Aurora Diamond Ring', '18k white gold ring with certified diamonds.', 2499.00, 'assets/images/ring1.jpg', 'rings', 10, 1, 'active'),
('Luna Pearl Necklace', 'Handpicked pearls with rose gold clasp.', 899.00, 'assets/images/necklace1.jpg', 'necklaces', 15, 1, 'active'),
('Solstice Gold Bracelet', '24k gold bracelet with intricate design.', 1799.00, 'assets/images/bracelet1.jpg', 'bracelets', 8, 1, 'active'),
('Eclipse Silver Earrings', 'Sterling silver earrings with minimalist style.', 199.00, 'assets/images/earrings1.jpg', 'earrings', 30, 1, 'active');


